# Admittance parameters for one mass damper systems
# the arm with params (mass_arm, damping_arm), connected by a
# spring-damper with parameters (damping_coupling, stiffness_coupling,
# equilibrium_point_spring)

mass_arm: [6,0,0,0,0,0,
           0,6,0,0,0,0,
           0,0,6,0,0,0,
           0,0,0,1,0,0,
           0,0,0,0,1,0,
           0,0,0,0,0,.5]
damping_coupling: [20,0,0,0,0,0,
                   0,20,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,10]
damping_arm: [60,0,0,0,0,0,
              0,60,0,0,0,0,
              0,0,60,0,0,0,
              0,0,0,15,0,0,
              0,0,0,0,15,0,
              0,0,0,0,0,15]
stiffness_coupling: [0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,10,0,0,
                     0,0,0,0,10,0,
                     0,0,0,0,0,10]

# [position (x, y, z)  orientation (x, y, z, w)]

# this equilibrium point is derived from setting all joints to -90 degree
equilibrium_point_spring: [0.111,0.494,0.587, 0.707, 0.004, 0.707, 0.010]


# this will limit the workspace ([x_min x_max y_min y_max z_min z_max])
#workspace_limits: [-0.30, 0.30, 0.35, 0.55, 0.20, 0.75] # conservative choice
workspace_limits: [-0.50, 0.50, -0.5, 0.5, 0.1, 0.483]

arm_max_vel: 1.5
arm_max_acc: 1.0

